version: '3.8'

services:
  app:
    build: .
    container_name: product-elasticsearch
    env_file:
      - .env
    ports:
      - '8080:8080'
    volumes:
      - .:/app  # Mount the current directory into the container
    depends_on:
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    image: elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Disable es security
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9200']
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s

  kibana:
    image: kibana:8.12.2
    container_name: kibana
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false # Disable Kibana security
volumes:
  esdata:
    driver: local
