basePath: /
definitions:
  models.Product:
    description: Represents a product object
    properties:
      company:
        type: string
      created_at:
        type: string
      drug_generic:
        type: string
      id:
        type: integer
      product_name:
        type: string
      score:
        type: number
      updated_at:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: This is a swagger for the service
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Elastic Search Skill-Test
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Checks the health of the service and returns a status message
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health Check
      tags:
      - Health
  /product:
    get:
      consumes:
      - application/json
      description: Retrieves a list of products with optional pagination and search
        keywords
      parameters:
      - description: Limit number of results
        in: query
        name: limit
        type: integer
      - description: Offset for pagination
        in: query
        name: offset
        type: integer
      - description: Search keyword
        in: query
        name: keyword
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Product'
            type: array
      summary: Get Products
      tags:
      - Products
swagger: "2.0"
